// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2LH7a-sNqMTdR4zUoNDrAA6SxooGpsG8',
    appId: '1:838548686799:web:914c809dd907f5fb54b4ba',
    messagingSenderId: '838548686799',
    projectId: 'logzine-c8905',
    authDomain: 'logzine-c8905.firebaseapp.com',
    storageBucket: 'logzine-c8905.firebasestorage.app',
    measurementId: 'G-SPV1X05N4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr2OEvuBRxX5_YzB8mPW4J3u1TITZ4zDY',
    appId: '1:838548686799:android:398e3a045d2422ad54b4ba',
    messagingSenderId: '838548686799',
    projectId: 'logzine-c8905',
    storageBucket: 'logzine-c8905.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4FxNJVQGcqd5PVAIFVJ72H_b32ig0HwE',
    appId: '1:838548686799:ios:92f7ae4998695fbb54b4ba',
    messagingSenderId: '838548686799',
    projectId: 'logzine-c8905',
    storageBucket: 'logzine-c8905.firebasestorage.app',
    iosBundleId: 'com.example.logzineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4FxNJVQGcqd5PVAIFVJ72H_b32ig0HwE',
    appId: '1:838548686799:ios:92f7ae4998695fbb54b4ba',
    messagingSenderId: '838548686799',
    projectId: 'logzine-c8905',
    storageBucket: 'logzine-c8905.firebasestorage.app',
    iosBundleId: 'com.example.logzineApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2LH7a-sNqMTdR4zUoNDrAA6SxooGpsG8',
    appId: '1:838548686799:web:8a2749d0add1ab4954b4ba',
    messagingSenderId: '838548686799',
    projectId: 'logzine-c8905',
    authDomain: 'logzine-c8905.firebaseapp.com',
    storageBucket: 'logzine-c8905.firebasestorage.app',
    measurementId: 'G-2G8FX0FPGY',
  );
}
